name: main

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install expect
        run: sudo apt-get install -y expect

      - name: Run QEMU OpenBSD installation
        run: ./qemu.exp
        timeout-minutes: 30
